### - CREATE CLIENT
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "<change name>",
  "email": "<change email>"
}

### - CREATE ACCOUNT
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "<add_client_id>"
}


### - CREATE TRANSACTION
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "2161e2cf-27ba-46f2-aab7-950c00dacabf",
  "account_id_to": "b06936c1-89d4-49dc-a480-c7381e25b582",
  "amount": 120
}